name: address_module
description: A new Flutter package project.
version: 2.8.4
repository: https://mub.mule.app
homepage: https://mub.mule.app
publish_to: https://mub.mule.app
environment:
  sdk: '>=2.17.6 <3.3.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  mule_theme:
    hosted: https://mub.mule.app
    version: ^1.0.4
  auth_module:
    hosted: https://mub.mule.app
    version: ^4.0.5
  mule_widgets:
    hosted: https://mub.mule.app
    version: ^2.7.1
  mule_common:
    hosted: https://mub.mule.app
    version: ^2.4.1
  provider: ^6.0.2
  routemaster: ^1.0.1
  flutter_svg: ^1.0.3
  amazon_cognito_identity_dart_2: ^3.0.3
  dio: ^4.0.6
  uuid: ^3.0.6
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  flutter_lints: ^2.0.0
  http_mock_adapter: ^0.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mocks/
    - assets/icons/
